version: '3'

services:
  web:
    volumes:
      - ./:/app
      - geoip2:/geoip2
    command: python manage.py runserver 0.0.0.0:8000 --settings=settings.dev
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  celery:
    volumes:
      - ./:/app
      - celery_data:/var/run/celery/
    command: >
      celery -A zeesilver worker
      -E
      -l info
      --pidfile=/var/run/celery/celeryworker.pid
    env_file:
      - ./.env.dev
    entrypoint: /app/wait-for-db.sh

  celery-beat:
    volumes:
      - ./:/app
      - celery_data:/var/run/celery/
    command: >
      celery -A zeesilver beat
      -l info
      --schedule=/var/run/celery/celerybeat-schedule
      --pidfile=/var/run/celery/celerybeat.pid
    env_file:
      - ./.env.dev
    entrypoint: /app/wait-for-db.sh

  db:
    image: postgres:12.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=zee
      - POSTGRES_PASSWORD=zee
      - POSTGRES_DB=zee_dev

volumes:
  app:
  postgres_data:
  celery_data:
  geoip2:
