# Generated by Django 3.0.6 on 2020-05-14 14:55

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200513_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='listings_li_search__219da8_gin'),
        ),
    ]
