# Generated by Django 3.0.6 on 2020-05-15 05:28

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200514_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
