# Generated by Django 3.0.6 on 2020-05-21 07:20

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20200515_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
