# Generated by Django 3.0.6 on 2020-05-26 12:04

import django.core.validators
from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator('^\\(?[2-9]\\d{2}\\)?\\s?\\d{3}(?:\\-|\\s)?\\d{4}$', message='Please enter a valid US phone number, including area code')])),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=32)),
                ('state', localflavor.us.models.USStateField(max_length=2)),
                ('zip_code', localflavor.us.models.USZipCodeField(max_length=10)),
                ('number', models.CharField(blank=True, max_length=16)),
                ('status', models.PositiveIntegerField(choices=[(1, 'Unpaid'), (2, 'Paid'), (3, 'Shipped'), (0, 'Cancelled')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
