# Generated by Django 3.0.6 on 2020-05-27 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, 'Unpaid'), (2, 'Paid'), (3, 'Shipped'), (0, 'Canceled')], default=1),
        ),
    ]
