# Generated by Django 3.0.6 on 2020-06-05 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'shipping provider', 'verbose_name_plural': 'shipping provider'},
        ),
    ]
